apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
    - name: "dev"
      sequences:
      - name: "delivery"
        tasks: 
        - name: deployment
        - name: test
        - name: "approval"
          properties: 
            pass: manual
            warning: manual
        - name: "release"

    - name: "hardening"
      sequences:
      - name: "delivery"
        triggeredOn:
          - event: "dev.delivery.finished"
        tasks: 
        - name: deployment
          properties: 
            deploymentstrategy: direct
        - name: "test"
          properties:
            teststrategy: "performance"
        - name: "approval"
          properties: 
            pass: automatic
            warning: automatic
        - name: "release"

    - name: "production"
      sequences:
      - name: "delivery"
        triggeredOn:
          - event: "hardening.delivery.finished"
        tasks: 
        - name: deployment
          properties: 
            deploymentstrategy: user_managed
        - name: rollback
        - name: "approval"
          properties: 
            pass: automatic
            warning: automatic
        - name: "release"
